// Generated by CoffeeScript 1.6.1
(function() {
  /CampaignDBsetup/;
  module.exports = {
    advertiser: String,
    program: String,
    flight: {
      startDate: Date,
      endDate: Date
    },
    geoCodes: [],
    keywords: [],
    active: Boolean,
    lastUpdated: Date
  };

}).call(this);
